name: ayon-hub
services:
- name: postgres
  environment_slug: docker
  dockerfile_path: Dockerfile
  github:
    repo: library/postgres
    branch: 16
  health_check:
    http_path: /api/info
  envs:
  - key: POSTGRES_USER
    value: ${POSTGRES_USER}
    scope: RUN_AND_BUILD_TIME
  - key: POSTGRES_PASSWORD
    value: ${POSTGRES_PASSWORD}
    scope: RUN_AND_BUILD_TIME
  - key: POSTGRES_DB
    value: ${POSTGRES_DB}
    scope: RUN_AND_BUILD_TIME
- name: redis
  environment_slug: docker
  dockerfile_path: Dockerfile
  github:
    repo: library/redis
    branch: alpine
  health_check:
    http_path: /api/info
- name: server
  environment_slug: docker
  dockerfile_path: Dockerfile
  github:
    repo: ynput/ayon
    branch: dev
  health_check:
    http_path: /api/info
  envs:
  - key: POSTGRES_USER
    value: ${POSTGRES_USER}
    scope: RUN_AND_BUILD_TIME
  - key: POSTGRES_PASSWORD
    value: ${POSTGRES_PASSWORD}
    scope: RUN_AND_BUILD_TIME
  - key: POSTGRES_DB
    value: ${POSTGRES_DB}
    scope: RUN_AND_BUILD_TIME
  routes:
  - path: /
